services:
  mongo:
    image: mongo:6
    container_name: mongo_yahoo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo:/docker-entrypoint-initdb.d

  llm:
    build: ./LLM
    container_name: dummy_LLM
    ports:
      - "6000:6000"
    depends_on:
      - mongo

  cache:
    build: ./cache
    container_name: cache
    ports:
      - "5000:5000"
    command: ["--policy", "lru", "--size", "500", "--mongo", "mongodb://mongo:27017/"]
    depends_on:
      - mongo
      - llm

  
  generador:
    build: ./generador
    container_name: generador_yahoo
    command: ["--dist", "poisson"]
    depends_on:
      - cache

volumes:
  mongo_data:
